### ISSUE TITLE
Got an error on SDK 5.1.0 during initialization

### ISSUE THREAD

**Issue by egenia** [Pushwoosh/pushwoosh-appcelerator-titanium#12]
Hello

During initialization, I got this error : 
[ERROR] :  2015-12-14 15:56:07.464 iNeed[79580:10897922] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSError boundBridge:withKrollObject:]: unrecognized selector sent to instance 0x7ff8db91a860'
[ERROR] :  **\* First throw call stack:
[ERROR] :  (
[ERROR] :   0   CoreFoundation                      0x000000010aa1ce65 **exceptionPreprocess + 165
[ERROR] :   1   libobjc.A.dylib                     0x000000010a3eedeb objc_exception_throw + 48
[ERROR] :   2   CoreFoundation                      0x000000010aa2548d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
[ERROR] :   3   CoreFoundation                      0x000000010a97290a ___forwarding_** + 970
[ERROR] :   4   CoreFoundation                      0x000000010a9724b8 _CF_forwarding_prep_0 + 120
[ERROR] :   5   iNeed                               0x0000000104c981e4 -[KrollBridge registerProxy:krollObject:] + 196
[ERROR] :   6   iNeed                               0x0000000104c982d7 -[KrollBridge registerProxy:] + 231
[ERROR] :   7   iNeed                               0x0000000104ed3868 TiBindingTiValueFromProxy + 280
[ERROR] :   8   iNeed                               0x0000000104ed370c TiBindingTiValueFromNSObject + 3260
[ERROR] :   9   iNeed                               0x0000000104ed2959 TiBindingTiValueFromNSDictionary + 457
[ERROR] :   10  iNeed                               0x0000000104ed3088 TiBindingTiValueFromNSObject + 1592
[ERROR] :   11  iNeed                               0x0000000104ca5267 ConvertIdTiValue + 55
[ERROR] :   12  iNeed                               0x0000000104ca6fe5 +[KrollObject toValue:value:] + 37
[ERROR] :   13  iNeed                               0x0000000104c9a9e0 -[KrollCallback call:thisObject:] + 352
[ERROR] :   14  iNeed                               0x0000000105286ceb -[ComPushwooshModuleModule onDidFailToRegisterForRemoteNotificationsWithError:] + 132
[ERROR] :   15  Foundation                          0x0000000106d11067 __NSThreadPerformPerform + 283
[ERROR] :   16  CoreFoundation                      0x000000010a948a31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
[ERROR] :   17  CoreFoundation                      0x000000010a93e8d7 __CFRunLoopDoSources0 + 423
[ERROR] :   18  CoreFoundation                      0x000000010a93de13 __CFRunLoopRun + 867
[ERROR] :   19  CoreFoundation                      0x000000010a93d828 CFRunLoopRunSpecific + 488
[ERROR] :   20  GraphicsServices                    0x000000010b872ad2 GSEventRunModal + 161
[ERROR] :   21  UIKit                               0x0000000107149610 UIApplicationMain + 171
[ERROR] :   22  iNeed                               0x0000000104c7ed56 main + 310
[ERROR] :   23  libdyld.dylib                       0x000000010b4ce92d start + 1
[ERROR] :   24  ???                                 0x0000000000000001 0x0 + 1
[ERROR] :  )
[ERROR] :  libc++abi.dylib: terminating with uncaught exception of type NSException

I have include last version of Pushwoosh, and in my controller, I have only :
var pushnotifications = require('com.pushwoosh.module');
Ti.API.info("module is => " + pushnotifications);

pushnotifications.pushNotificationsRegister({
    "pw_appid": "<my appId>",
    success:function(e)
    {
        Ti.API.info('JS registration success event: ' + e.registrationId);
    },
    error:function(e)
    {
        Ti.API.error("Error during registration: "+e.error);
    },
    callback:function(e) // called when a push notification is received
    {
        Ti.API.info('JS message event: ' + JSON.stringify(e.data));
    }
});

Any idea on that ?

**Comment by shaders** [comment]
Checking

**Comment by egenia** [comment]
Any idea on that ?
