### ISSUE TITLE
Open source the titanium modules

### ISSUE THREAD

**Issue by hansemannn** [Pushwoosh/pushwoosh-appcelerator-titanium#13]
Hey guys,

as a lot of people are currently moving from Parse to other services (like yours), the Titanium community is very interested in using your module in the future. To increase it's usage and the backup by the native module developer, I would welcome to see the module open sources. 

Otherwise, I would just create a new module based on the iOS SDK, but working with the "original" one would be much nicer.

What are your thoughts on this? Thanks!

Hans

**Comment by shaders** [comment]
Hi,

I'm not sure I understand you. Do you want Pushwoosh module to be a part of Titanium SDK or something else?
Though I like the idea of sharing the source of the module.

**Comment by hansemannn** [comment]
Not exactly. Currently, the module is available [packaged](https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/tree/master/Push-Notifications-Module/modules/iphone/com.pushwoosh.module/1.1.0) with a closed source. Making it open-source would allow it other devs to extend the module by submitting a PR (like in other projects).

**Comment by shaders** [comment]
I see, just wondering if there is anything in particular you want to change/add to the module?

**Comment by shaders** [comment]
https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/tree/master/Module-Source
Let me know your feedback.

**Comment by hansemannn** [comment]
Yes, thank you! There are some validation macros you could use to simplify the proxy validation. A lot of community users appreciate it to see the module open source. I will setup a PR over the weekend to propose something and you can check it if you want. Thanks!

**Comment by shaders** [comment]
Thanks! Looking forward to it.

**Comment by shaders** [comment]
@hansemannn hi, I wonder if you could help me with this ticket? Maybe you have any kind on information there?

https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/issues/19#issuecomment-204425484

**Comment by hansemannn** [comment]
Hey there, I only changed the iOS part of the module, Android remained the same.

**Comment by shaders** [comment]
I know, maybe you know what is the reason for the problem? It looks something confuses titanium internally.... maybe titanium itself.
