### ISSUE TITLE
android <5.0 support?

### ISSUE THREAD

**Issue by faelos** [Pushwoosh/pushwoosh-appcelerator-titanium#14]
Hi there,

Thanks for keeping the module up to date. A bit of a rarity with TI :)

Integration has been very easy thanks to all the logging! One thing though - I have a couple of android devices on ~v4.4. Both failed to register. Upgraded one to lollipop and is now working. By no means a deal breaker but are you able to confirm <5.0 is not supported?

Cheers,
Greg

**Comment by shaders** [comment]
Hi,

Any chance to get the logs from the console on 4.4? It should work.

**Comment by faelos** [comment]
Hey,

Who would have thought that logging to an external file would fix the issue....ahem...
Is working! Sorry to bother you. Maybe the wifi was down :)

Thanks.
