### ISSUE TITLE
Android icon

### ISSUE THREAD

**Issue by macasfaj** [Pushwoosh/pushwoosh-appcelerator-titanium#16]
When I install the module for Android, I register my App successfully. 

Then I send a push from Pushwoosh panel, but the App icon is not shown in the push.

I try without icon, "appicon", "appicon.png" and "images/appicon.png"... It always show a white square icon. :(

**Comment by DimanAM** [comment]
This issue is documented here http://docs.pushwoosh.com/docs/android-faq#how-to-set-a-notification-icon-in-android-lollipop

**Comment by macasfaj** [comment]
Thanks, it's fixed. :)
