### ISSUE TITLE
Optional logging?

### ISSUE THREAD

**Issue by rborn** [Pushwoosh/pushwoosh-appcelerator-titanium#22]
Could we have an option we could set in JS to display or not the logs? 
While during development this is fine, in production the logs should not be there.

Thank you.

**Comment by shaders** [comment]
You can control logs level this way:
iOS: http://docs.pushwoosh.com/docs/native-ios-sdk
look for (Controlling Log Level)
Android: http://docs.pushwoosh.com/docs/androidmanifestxml-modifications
look for (Controlling Log Level)

**Comment by rborn** [comment]
And this applies to the titanium module as well?
I'll try, thank you 😄

**Comment by rborn** [comment]
@shaders it worked, thank you!
