### ISSUE TITLE
Improvements to handling on google-play-services.jar

### ISSUE THREAD

**Issue by beaur** [Pushwoosh/pushwoosh-appcelerator-titanium#24]
I see a few issues here with conflicts on the `google-play-services.jar`.

It seems these conflicts have been resolved in other modules such as `ti.map`, `ti.admob` etc by splitting up this jar file and only including the parts needed.  

Another example is the Ti.GA module which replaced `google-play-services.jar` with 
`google-play-services-base.jar` and `google-play-services-analytics.jar`
https://github.com/benbahrenburg/Ti.GA/pull/6

This is where `ti.map` fixed the issue https://github.com/appcelerator-modules/ti.map/pull/113/commits/55adee377b41e0556ba96fdc4678faf3a9f1ce13

Could we have `google-play-services.jar` lib removed and replaced with just the parts being used?  I think that should fix a lot of common conflicts.

**Comment by beaur** [comment]
This great article might also be of help https://medium.com/all-titanium/deal-with-titanium-modules-and-its-missing-support-for-android-multidex-546de5486d13

**Comment by viridanti** [comment]
Fixed.
