### ISSUE TITLE
Clarify gcm_projectid parameter and update sample code

### ISSUE THREAD

**Issue by beaur** [Pushwoosh/pushwoosh-appcelerator-titanium#25]
I found this very confusing as it is actually the project NUMBER not the project ID.

I eventually realised it is documented here: http://docs.pushwoosh.com/docs/gcm-configuration

However it is not even included in the sample code here: http://docs.pushwoosh.com/docs/appcelerator-titanium
(which does however include the setTimeout workaround for thread issues)

And the sample code here: https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/blob/master/Titanium-Sample-iOS-Android/app/controllers/index.js
does not include the setTimeout workaround but does include a project id parameter.

Would be nice if your sample code was accurate and at least included a comment to avoid the project number / project id confusion.  Ideally we could rename the parameter and include links to where to find it.  The screenshots on the first link on where to find it within the console are also outdated.  It is now hidden under IAM & Admin > [Your project] > Settings > Project number

**Comment by viridanti** [comment]
Starting from the version 2.0.0 the "gcm_project" field is being used in the sample. Thanks!
