### ISSUE TITLE
Not working on older Android versions

### ISSUE THREAD

**Issue by beaur** [Pushwoosh/pushwoosh-appcelerator-titanium#29]
I ran the test app on three devices after updating it with my pushwoosh app ID and GCM project ID.

Nexus 5X Android 7:
Push message was delivered successfully

Nexus 5 Android 5:
Samsung Galaxy S3 Android 4.4:
Devices registers ok but never gets the push message once it is sent.

What am I missing here?  Why are push notifications not coming through to these devices?

**Comment by beaur** [comment]
Never mind, seems to be related to the wifi network I was on.  Company had blocked some ports that GCM uses I think.

**Comment by shaders** [comment]
The easiest check for this is to switch device to 3G only (turn Wi-Fi off) and check.

**Comment by beaur** [comment]
Yeah I would have done this expect the devices were wifi only and didn't have sim cards in them.

**Comment by beaur** [comment]
Thanks for the help anyway.
