### ISSUE TITLE
Problem related with setTags method

### ISSUE THREAD

**Issue by juanblo** [Pushwoosh/pushwoosh-appcelerator-titanium#3]
Hi, 

I'm using the module version 1.0 and 1.1 but on iOS I'm getting this error using the setTags method:

[ERROR] Pushwoosh: Invalid argument. Expected argument of type NSDictionary
[ERROR] tags must be NSDictionary

The code used is:

``` javascript
var city = "bogota";
pushNotifications.setTags({city_slug: city});
```

I've trying with quotes:

``` javascript
var city = "bogota";
pushNotifications.setTags({"city_slug": city});
```

but the error persist (only on iOS). Some idea to fix this ? Thx

**Comment by juanblo** [comment]
Hi guys, 

Any news about this bug ?

**Comment by shaders** [comment]
Please try the updated version, the bug should be fixed there. (The plugin version still the same yet).

**Comment by juanblo** [comment]
Hi shaders, 

Thanks, it works !
