### ISSUE TITLE
iOS 10 - Unregister and re-register won't register the device again

### ISSUE THREAD

**Issue by rborn** [Pushwoosh/pushwoosh-appcelerator-titanium#33]
[This seems to be a recurrent issue on the native side](https://community.pushwoosh.com/questions/3921/re-registering-device-fails-on-ios).

I updated the module to use the 4.2.0 version of the iOS sdk and the issue persists.
This happens on iOS 10.1 (iPad mini retina if this matters).

**Comment by wfhm** [comment]
Hi,

It seems to be out of our control. Please refer to the following issue:

https://github.com/Pushwoosh/pushwoosh-unity/issues/18#issuecomment-255362579

Re-registering shortly after unregistering (approx. one minute) works as expected.
