### ISSUE TITLE
Rebuild with Titanium 6

### ISSUE THREAD

**Issue by HazemKhaled** [Pushwoosh/pushwoosh-appcelerator-titanium#36]
Android modules need to rebuild with Titanium 6.0.0.GA, modules built with less that this SDK will not work with latest one

How to
http://skypanther.com/2016/10/rebuilding-modules-for-titanium-6/

**Comment by shaders** [comment]
fixed via https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/commit/8e2a867bdd462706bf4175ba5e6d60f09862d2a3
