### ISSUE TITLE
Start a force closed App when a notification is received WITHOUT tapping the notification

### ISSUE THREAD

**Issue by pakoArtal** [Pushwoosh/pushwoosh-appcelerator-titanium#51]
Hi,

Would it be possible to start in the background a force closed Appcelerator App when a notification is received WITHOUT tapping the notification?

I'm looking for something similar to the force-start payload in https://github.com/phonegap/phonegap-plugin-push/blob/3398120e2c6848a6e96267d083f5011f0c0f6f71/docs/PAYLOAD.md#application-force-closed

Thank you!

**Comment by wfhm** [comment]
Hi,

It is currently not possible due to platform limitations.
