### ISSUE TITLE
Pushwoosh notifications module cause conflicts with other notifications modules in iOS 11

### ISSUE THREAD

**Issue by rpenates** [Pushwoosh/pushwoosh-appcelerator-titanium#52]
Hi,
I've facing a issue with the integration of some modules in a titanium app, specifically plotprojects and pushwoosh. The issue consist in the notification listener of the plotprojects module stops working after pushwoosh notifications module is initialized in iOS 11. According to that i opened an issue in the plotprojects module repository hosted in github.
After a while the plotprojects team answered that they found a problem with the didReceiveNotificationResponse method of the UNUserNotificationCenter in the pushwoosh module implementation. 

Here is the related issue: https://github.com/Plotprojects/plot-titanium-module/issues/6

Regards.

**Comment by wfhm** [comment]
Hi,

Checking it.

**Comment by rpenates** [comment]
Hi again, 
Have you found something about the issue?

**Comment by wfhm** [comment]
@rpenates 

Not yet. I will update you on a state of the investigation as soon as possible.

**Comment by wfhm** [comment]
@rpenates Fixed in 5.5.2.
