### ISSUE TITLE
Class not found Exception

### ISSUE THREAD

**Issue by phobeous** [Pushwoosh/pushwoosh-appcelerator-titanium#53]
com.pushwoosh.module - 5.4.1
On Samsung Galaxy S8 with Android 7.0, I get the following exception
>Pushwoosh: Exception occurred
12-12 09:11:12.540 12514 12514 E Pushwoosh: java.lang.ClassNotFoundException: com.pushwoosh.module.NotificationFactory
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at java.lang.Class.classForName(Native Method)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at java.lang.Class.forName(Class.java:400)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at java.lang.Class.forName(Class.java:326)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at com.pushwoosh.internal.preference.PreferenceClassValue.<init>(Unknown Source)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at com.pushwoosh.a.h.<init>(Unknown Source)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at com.pushwoosh.a.p.a(Unknown Source)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at com.pushwoosh.e.<init>(Unknown Source)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at com.pushwoosh.e.<init>(Unknown Source)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at com.pushwoosh.e$a.a(Unknown Source)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1759)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1734)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6420)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6012)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5951)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at android.os.Looper.loop(Looper.java:154)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at java.lang.reflect.Method.invoke(Native Method)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
12-12 09:11:12.540 12514 12514 E Pushwoosh: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.module.NotificationFactory" on path: DexPathList[[zip file "/data/app/com.my.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.my.app-2/lib/arm, /data/app/com.my.app-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-12 09:11:12.540 12514 12514 E Pushwoosh: 	... 23 more

Class com.pushwoosh.internal.preference.PreferenceClassValue may be instantiating com.pushwoosh.module.NotificationFactory which is not present in latest module version.

**Comment by wfhm** [comment]
@phobeous 

This is a handled exception which occurs when you upgrade your Pushwoosh SDK 4.12+ to the lates one. It does not break any Pushwoosh SDK functionality, so you can safely ignore it.

Please let me know if this issue leads to unexpected behavior of your app.
