### ISSUE TITLE
[Bug] iOS - registerForPushNotifications 

### ISSUE THREAD

**Issue by juanagu** [Pushwoosh/pushwoosh-appcelerator-titanium#57]
module version: 5.5.3
Tested on iphone 6s with iOS 11.2.2
using this code:

`pushwoosh.registerForPushNotifications(function(e){},function(e){});`

onerror never called when user not allowed the notifications.

**Comment by wfhm** [comment]
Hi,

This is actually an expected behavior - iOS devices still subscribe for pushes even if a user does not allow showing push notifications, therefore error callback does not fire in this case. It only fires when a registration fails, e.g. due to poor internet connection.
