### ISSUE TITLE
AppInbox Support

### ISSUE THREAD

**Issue by joshualambert** [Pushwoosh/pushwoosh-appcelerator-titanium#58]
Does this module support AppInbox?

**Comment by wfhm** [comment]
Hi @joshualambert,

Do you mean our Pushwoosh Inbox feature? If so, it is not yet supported in Titanium module. If you meant something else, could you please provide a bit more details on your query?

**Comment by joshualambert** [comment]
Yes, I was referring to the "PushWoosh" inbox feature. Thanks for the information.

**Comment by wfhm** [comment]
@joshualambert 

The Inbox feature will be added to the plugin with the next release.
