### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by SquirrelMobile** [Pushwoosh/pushwoosh-appcelerator-titanium#59]
Do you plan to add GPDR support in Appcelerator Titanium module https://www.pushwoosh.com/v1.0/docs/the-gdpr-compliance ?

**Comment by wfhm** [comment]
Hi,

Sure, it will be added to Titanium with the next module release.

**Comment by wfhm** [comment]
@SquirrelMobile Apologies for the late notification. GDPR support was added in 5.8.0.
