### ISSUE TITLE
Migration from GCM to Firebase?

### ISSUE THREAD

**Issue by jfalcone** [Pushwoosh/pushwoosh-appcelerator-titanium#61]
Is anything going to be required to migrate from GCM to Firebase for Titanium module users or are the details all hidden under the covers of the module?  

According to Google, GCM is being retired as early as April 11, 2019...  please advise.

**Comment by wfhm** [comment]
Hey @jfalcone ,

This is indeed covered under the hood of the module, so it cannot be accessed without an access to SDK sources. 

Please note that we have already started migrating our plugins to FCM API, and expect it to be done by the end of February.

**Comment by wfhm** [comment]
@jfalcone the plugin is moved to FCM API with 5.12.0 release
