### ISSUE TITLE
iOS: Push notifications dialog does not show since v5.8.0

### ISSUE THREAD

**Issue by tomgiessel** [Pushwoosh/pushwoosh-appcelerator-titanium#69]
Hi there,

I am trying to update my Pushwoosh module from currently v5.5.5 to a newer version. With the current version (v5.5.5) everything works as expected. As soon as I use ANY newer version of the module (v5.8.0 up to v5.13.2), Pushwoosh does not prompt me with the permission dialog. Hence the callbacks for registerForPushNotifications are never called. I was unable to find any hints why this is the case. I even tried the sample app with the same result.

Tested on iPhone 6s with iOS 12.2 using different Titanium versions: 7.5.0, 7.5.2 and 8.0.0

Cheers,
Tom

**Comment by wfhm** [comment]
@tomgiessel Hi,

This is really strange, I've tried reproducing the issue with the latest version and it works just find for me (Titanium SDK 7.5.2GA and 8.0.0). By any chance may I ask you to try [our Titanium sample app](https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/tree/master/Titanium-Sample-iOS-Android) and let us know if the issue is reproducible with it?

**Comment by wfhm** [comment]
@tomgiessel any updates?

**Comment by tomgiessel** [comment]
@wfhm Hi,

I experience the same issues with the Titanium sample app. When I use v5.5.5 of the Pushwoosh module + remove the geozones module it works as expected and I see the dialog. Here is what I see when using the sample app (untouched), no error, no nothing:

<img width="707" alt="Bildschirmfoto 2019-04-23 um 10 54 52" src="https://user-images.githubusercontent.com/2423055/56568061-861cd300-65b6-11e9-93a4-15ae1901b09a.png">

![Image from iOS](https://user-images.githubusercontent.com/2423055/56568053-7ef5c500-65b6-11e9-9aca-82d206d1d8f9.png)

**Comment by wfhm** [comment]
Hello @tomgiessel ,

I am sorry for the delay in correspondence. I have just tried the sample and it still works just fine:
![IMG_1773](https://user-images.githubusercontent.com/13344781/57772299-43769280-773f-11e9-8ed1-a615b09d092d.PNG)

Could it be related to some configurations of your app? Could it be that push notifications are not enabled in Apple Developer portal for the App ID you use?

**Comment by tomgiessel** [comment]
Hi @wfhm,

unfortunately I don't see any configuration issue. As I said, as soon as I revert back to the v5.5.5 of the Pushwoosh module, it all works fine again. I will look more into this once I am working on the mobile app again. For now I have no idea whats causing this.

**Comment by wfhm** [comment]
@tomgiessel Did you manage to make it work with one of the latest releases? Also, the latest versions of the module now use FCM for Android, so it is strongly recommended to use 5.13.+ versions, otherwise Android might work incorrectly.

**Comment by wfhm** [comment]
Closed until there is more data to work with.
