### ISSUE TITLE
Please exclude games from google-play-services.jar

### ISSUE THREAD

**Issue by yhanssens** [Pushwoosh/pushwoosh-appcelerator-titanium#8]
When using this module for Android the number of field references exceed the 65k limit. Is it possible to re-build the google-play-services but without the games sections?

**Comment by DimanAM** [comment]
Yes. It's easy:

unzip google-play-services.jar -d tmp
jar cf gcm.jar tmp/com/google/android/gms/gcm/&#42;&#42;.class tmp/com/google/android/gms/iid/&#42;&#42;.class
rm -rf tmp/

You can find such library here https://github.com/Pushwoosh/pushwoosh-xamarin/blob/master/Android/PushwooshSDK/Jars/gcm.jar

**Comment by yhanssens** [comment]
Worked like a charm, thanks!
