### ISSUE TITLE
Failed to run dexer on Android

### ISSUE THREAD

**Issue by m4tt86** [Pushwoosh/pushwoosh-appcelerator-titanium#9]
When I compile my app with module "com.pushwoosh.module" enabled, I get this error from the console:

[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/signin/internal/zzg;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/signin/internal/zze;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/signin/internal/zzh;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/signin/internal/zze$zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/signin/internal/zzf;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/signin/internal/zzc;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/signin/internal/zzf$zza$zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/signin/internal/zzd$zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/signin/internal/zze$zza$zza;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :   at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR] :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR] :   at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR] :   at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR] :   at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :   at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR] :   ... 4 more
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/myuser/.appcelerator/install/5.0.3/package/node_modules/appc-cli-titanium/plugins/run.js:89:66)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)
[ERROR] Application Installer abnormal process termination. Process exit value was 1

**Comment by shaders** [comment]
It looks like you are using the other plugins that references Google-Play-Services.jar
The easiest one is simply to remove jar from the other plugins and use one copy of this jar file.

This jar could be located at:
modules/android/_module_name_/_version_/lib/google-play-services.jar

**Comment by JimmyDLA** [comment]
@shaders you a life saver bro!!! Had the same issue and was going crazy. Thank you!
