### ISSUE TITLE
iOS module update to Apple Silicon

### ISSUE THREAD

**Issue by macasfaj** [Pushwoosh/pushwoosh-appcelerator-titanium#90]
Using last release, 6.1.0, we can't run Apps on simulators without Rosetta.

We get this message:

_[ERROR] Error: The app is using native modules that do not support arm64 simulators and you are on an arm64 device:
- com.pushwoosh.module

It would be great if you could update the module, Thanks!

**Comment by rlustemberg** [comment]
I've made the following PR: https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/pull/91

**Comment by macasfaj** [comment]
Fixed! :)
